---
name: build-torrserver

#on:
#  release:
#    types: [published]

on: [push, pull_request]

jobs:
  checkTSVersion:
    runs-on: ubuntu-latest
    outputs:
      run_build_assets: ${{ steps.set_output.outputs.build_assets }}
      ts_version_latest: ${{ steps.set_output.outputs.ts_version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
        with:
          fetch-depth: 1
      - name: Get latest TorrServer version
        run: |
          TS_VERSION_LATEST="$(curl -sL https://api.github.com/repos/YouROK/TorrServer/releases/latest | jq -r '.tag_name')"
          echo "TS_VERSION_LATEST=${TS_VERSION_LATEST}" >> ${GITHUB_ENV}
      - name: Check assets version
        id: set_output
        working-directory: ./torrserver/assets
        run: |
          TS_VERSION_ASSETS=$(cat VERSION)
          echo "TS version latest: ${TS_VERSION_LATEST}"
          echo "TS version assets: ${TS_VERSION_ASSETS}"
          if [[ "$TS_VERSION_LATEST" != "$TS_VERSION_ASSETS" ]]; then
            echo "Latest version is not equal version in assets"
            echo "build_assets=true" >> "$GITHUB_OUTPUT"
            echo "ts_version=${TS_VERSION_LATEST}" >> "$GITHUB_OUTPUT"
          else
            echo "Latest version is the same as in assets"
            echo "build_assets=false" >> "$GITHUB_OUTPUT"
          fi

  buildAssets:
    needs: [ checkTSVersion ]
    if: needs.checkTSVersion.outputs.run_build_assets == 'true'
    runs-on: ubuntu-latest
    env:
      TS_VERSION: ${{ needs.checkTSVersion.outputs.ts_version_latest }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - uses: actions/setup-go@v5
        with:
          go-version: '^1.21.2'
      - name: Prepare TorrServer source
        working-directory: ./torrserver/.build
        run: |
          git clone --depth 1 --branch $TS_VERSION https://github.com/YouROK/TorrServer.git
          cp ./build-all.sh ./TorrServer/build-all.sh
      - name: Run build
        working-directory: ./torrserver/.build/TorrServer
        run: |
          ./build-all.sh
      - name: Copy assets
        working-directory: ./torrserver
        run: |
          rm -rf ./assets
          cp -r ./.build/TorrServer/dist ./assets
          echo $TS_VERSION > ./assets/VERSION
      - name: Commit assets
        uses: EndBug/add-and-commit@v9
        with:
          add: ./torrserver/assets
          message: 'chore: added assets'
