---
name: build-torrserver

on: [push, pull_request]
#on:
#  release:
#    types: [published]

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0

      - name: Prepare envs
        working-directory: ./torrserver
        run: |
          VERSION=$(grep '^version: \w' config.yaml | sed 's/^.*: //')
          echo "VERSION=${VERSION}" >> ${GITHUB_ENV}
          echo "VERSION_ADDON=$(echo $VERSION | cut -d "-" -f 1)" >> ${GITHUB_ENV}
          echo "VERSION_TS=$(echo $VERSION | cut -d "-" -f 2)" >> ${GITHUB_ENV}
          echo "VERSION_META=$(echo $VERSION | cut -d "-" -f 3)" >> ${GITHUB_ENV}
          echo "REPO=${GITHUB_REPOSITORY}" >> ${GITHUB_ENV}
          echo "Version: ${VERSION}"
          echo "Repo: ${GITHUB_REPOSITORY}"

      - name: Prepare source
        working-directory: ./torrserver/.build
        run: |
          rm -rf src
          echo "Clone TorrServer-${VERSION_TS}"
          git clone --depth 1 --branch $VERSION_TS https://github.com/YouROK/TorrServer.git src
          echo "Set relative path for staticfiles"
          jq -c '. + { "homepage": "./" }' ./src/web/package.json --indent 2 > ./src/web/package.$$.json
          mv ./src/web/package.$$.json ./src/web/package.json

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2.1.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.2.1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3.3.0
        with:
          context: ./torrserver/.build
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ env.REPO }}:${{ env.VERSION }}
            ghcr.io/${{ env.REPO }}:latest
          build-args: |
            VERSION: ${{ env.VERSION }}
